export const projectSelectOptions = {
  bookType: [
    "Kinderbuch",
    "Bilderbuch",
    "Malbuch",
    "Ausmalbuch",
    "Activity-Buch",
    "Rätselbuch",
    "Lernbuch",
    "Faktenbuch",
    "Sachbuch",
    "Ratgeber",
    "Roman",
    "Thriller",
    "Krimi",
    "Fantasy",
    "Science-Fiction",
    "Romance",
    "Historischer Roman",
    "Young Adult",
    "Biografie",
    "Memoir",
    "Kochbuch",
    "Reisebuch",
    "Workbook",
    "Journal",
    "Notizbuch",
    "Tagebuch",
    "Planer",
    "Kalender",
    "Logbuch",
    "Low-Content-Buch",
    "No-Content-Buch"
  ],
  topic: [
    "Abenteuer",
    "Freundschaft",
    "Liebe",
    "Familie",
    "Selbstfindung",
    "Neuanfang",
    "Erfolg",
    "Motivation",
    "Achtsamkeit",
    "Produktivität",
    "Gesundheit",
    "Fitness",
    "Ernährung",
    "Psychologie",
    "Business",
    "Finanzen",
    "Karriere",
    "Spiritualität",
    "Reisen",
    "Natur",
    "Umwelt",
    "Geschichte",
    "Wissenschaft",
    "Technologie",
    "Künstliche Intelligenz",
    "True Crime",
    "Mordfall",
    "Verschwörung",
    "Geheimnis",
    "Überleben",
    "Rache",
    "Dystopie",
    "Magie",
    "Weltenbau",
    "Weltraum",
    "Zeitreise",
    "Monster",
    "Drachen",
    "Detektivgeschichte",
    "Polizeiermittlung",
    "Gerichtsfall",
    "Kleinstadtgeheimnis",
    "Coming-of-Age",
    "Schule",
    "Lernen",
    "Konzentration",
    "Kreativität",
    "Zeichnen",
    "Mandala",
    "Tiere",
    "Dinosaurier",
    "Einhörner",
    "Fahrzeuge",
    "Berufe",
    "Jahreszeiten",
    "Feiertage",
    "Weihnachten",
    "Ostern",
    "Halloween",
    "Geburtstag",
    "Hochzeit",
    "Schwangerschaft",
    "Haushalt",
    "Garten",
    "Rezepte",
    "Dankbarkeit",
    "Gewohnheiten",
    "Ziele setzen",
    "Projektplanung",
    "Budgetplanung",
    "Fitness-Tracking",
    "Lesetagebuch",
    "Reisetagebuch",
    "Passwort-Logbuch",
    "Blutzucker-Logbuch",
    "Medikamenten-Tracker"
  ],
  targetAudience: [
    "Kleinkinder",
    "Kindergartenkinder",
    "Vorschulkinder",
    "Erstleser",
    "Grundschulkinder",
    "Teenager",
    "Young Adult",
    "Erwachsene",
    "Senioren",
    "Eltern",
    "Lehrer und Pädagogen",
    "Studierende",
    "Berufstätige",
    "Selbstständige",
    "Unternehmer",
    "Kreative",
    "Autorinnen und Autoren",
    "Hobbyisten",
    "Fantasy-Fans",
    "Thriller-Fans",
    "Romance-Leser",
    "Sachbuch-Leser",
    "KDP-Publisher",
    "Planer-Nutzer",
    "Menschen mit wenig Zeit",
    "Anfänger",
    "Fortgeschrittene",
    "Nischenpublikum"
  ],
  ageRange: [
    "0-2 Jahre",
    "2-3 Jahre",
    "3-4 Jahre",
    "4-6 Jahre",
    "5-7 Jahre",
    "6-8 Jahre",
    "7-9 Jahre",
    "8-10 Jahre",
    "9-12 Jahre",
    "12-14 Jahre",
    "14-16 Jahre",
    "16-18 Jahre",
    "18+",
    "18-35 Jahre",
    "25-45 Jahre",
    "35-55 Jahre",
    "50+",
    "Alle Altersgruppen"
  ],
  language: [
    "Deutsch",
    "Deutsch (einfache Sprache)",
    "Deutsch (gehobener Stil)",
    "Deutsch (locker und modern)",
    "Englisch",
    "Englisch (US)",
    "Englisch (UK)",
    "Spanisch",
    "Französisch",
    "Italienisch",
    "Niederländisch",
    "Polnisch",
    "Türkisch",
    "Portugiesisch",
    "Mehrsprachig Deutsch/Englisch"
  ],
  bookFormat: [
    "E-Book",
    "Taschenbuch",
    "Hardcover",
    "KDP Paperback 5 x 8 Zoll",
    "KDP Paperback 6 x 9 Zoll",
    "KDP groß 8,5 x 11 Zoll",
    "KDP quadratisch 8,5 x 8,5 Zoll",
    "A4",
    "A5",
    "US Letter",
    "Pappbilderbuch",
    "Bilderbuch",
    "Vorlesebuch",
    "Erstlesebuch",
    "Gute-Nacht-Geschichte",
    "Romanformat",
    "Workbook-Format",
    "Journal-Format",
    "Notizbuch liniert",
    "Notizbuch kariert",
    "Notizbuch punktkariert",
    "Blanko-Notizbuch",
    "Planer Tagesansicht",
    "Planer Wochenansicht",
    "Planer Monatsansicht",
    "Doppelseiten-Layout",
    "Einzelseiten-Layout",
    "Ausmalbuch mit einseitigem Druck",
    "Rätselbuch mit Lösungen"
  ],
  pageCount: [
    "12",
    "16",
    "20",
    "24",
    "28",
    "32",
    "36",
    "40",
    "48",
    "56",
    "64",
    "80",
    "96",
    "100",
    "120",
    "150",
    "180",
    "200",
    "240",
    "300",
    "365"
  ],
  narrativePerspective: [
    "Nicht erzählend / strukturierter Inhalt",
    "Ich-Perspektive",
    "Dritte Person",
    "Personaler Erzähler",
    "Allwissender Erzähler",
    "Multiperspektivisch",
    "Wechselnde Perspektiven",
    "Direkte Ansprache des Lesers",
    "Dialogbetont",
    "Tagebuchform",
    "Brief-/E-Mail-Form",
    "Reportage-Stil",
    "Sachlich erklärend",
    "Schritt-für-Schritt-Anleitung",
    "Workbook-Anleitung",
    "Minimaler Text",
    "Reimform",
    "Märchenhafte Erzählweise"
  ],
  styleAndTone: [
    "Warm, klar und altersgerecht",
    "Professionell und sachlich",
    "Locker und modern",
    "Humorvoll und verspielt",
    "Spannend und temporeich",
    "Düster und atmosphärisch",
    "Psychologisch intensiv",
    "Romantisch und emotional",
    "Episch und bildgewaltig",
    "Magisch und fantasievoll",
    "Minimalistisch und klar",
    "Motivierend und ermutigend",
    "Pädagogisch und strukturiert",
    "Poetisch und literarisch",
    "Praktisch und handlungsorientiert",
    "Luxuriös und hochwertig",
    "Frech und lebendig",
    "Ruhig und reflektierend",
    "Inspirierend und achtsam",
    "Kompakt und direkt",
    "Einfach und sehr verständlich",
    "Wissenschaftlich fundiert",
    "Storytelling-orientiert",
    "Visuell gedacht mit wenig Text",
    "KDP-marktorientiert"
  ]
};
