export const projectSelectOptions = {
  bookType: ["Kinderbuch"],
  topic: [
    "Abenteuer",
    "Freundschaft",
    "Mut",
    "Selbstvertrauen",
    "Familie",
    "Geschwister",
    "Einschlafen",
    "Träume",
    "Gefühle verstehen",
    "Wut und Versöhnung",
    "Angst überwinden",
    "Teilen lernen",
    "Hilfsbereitschaft",
    "Ehrlichkeit",
    "Geduld",
    "Dankbarkeit",
    "Neugier",
    "Kreativität",
    "Magie",
    "Tiere",
    "Wald",
    "Meer",
    "Weltraum",
    "Dinosaurier",
    "Feen und Zauberwesen",
    "Detektivgeschichte",
    "Schule und Kindergarten",
    "Umwelt und Natur",
    "Jahreszeiten",
    "Geburtstag",
    "Weihnachten",
    "Ostern",
    "Erster Schultag",
    "Reisen",
    "Vielfalt und Akzeptanz",
    "Gesundheit und Körper",
    "Ernährung",
    "Ordnung lernen",
    "Sicherheit im Alltag"
  ],
  targetAudience: [
    "Kleinkinder",
    "Kindergartenkinder",
    "Vorschulkinder",
    "Erstleser",
    "Grundschulkinder",
    "Kinder mit Vorlesebegleitung",
    "Kinder, die selbst lesen",
    "Eltern und Kinder gemeinsam",
    "Pädagogische Einrichtungen",
    "Familien mit mehreren Kindern"
  ],
  ageRange: [
    "0-2 Jahre",
    "2-3 Jahre",
    "3-4 Jahre",
    "4-6 Jahre",
    "5-7 Jahre",
    "6-8 Jahre",
    "7-9 Jahre",
    "8-10 Jahre",
    "9-12 Jahre"
  ],
  language: [
    "Deutsch",
    "Deutsch (einfache Sprache)",
    "Deutsch (Reimform)",
    "Englisch",
    "Spanisch",
    "Französisch",
    "Italienisch",
    "Niederländisch",
    "Polnisch",
    "Türkisch"
  ],
  bookFormat: [
    "Pappbilderbuch",
    "Bilderbuch",
    "Vorlesebuch",
    "Erstlesebuch",
    "Gute-Nacht-Geschichte",
    "Reimbuch",
    "Lernbuch",
    "Abenteuergeschichte",
    "Kurzes Kinderbuch",
    "KDP Paperback 6 x 9 Zoll",
    "KDP quadratisch 8,5 x 8,5 Zoll",
    "KDP groß 8,5 x 11 Zoll",
    "Doppelseiten-Layout",
    "Einzelseiten-Layout"
  ],
  pageCount: ["12", "16", "20", "24", "28", "32", "36", "40", "48", "56", "64"],
  narrativePerspective: [
    "Dritte Person",
    "Ich-Perspektive",
    "Wir-Perspektive",
    "Allwissender Erzähler",
    "Personaler Erzähler",
    "Direkte Ansprache des Kindes",
    "Dialogbetont",
    "Reimender Erzähler",
    "Tagebuchähnlich",
    "Märchenhafte Erzählweise"
  ],
  styleAndTone: [
    "Warm, klar und altersgerecht",
    "Liebevoll und beruhigend",
    "Humorvoll und verspielt",
    "Abenteuerlich und spannend",
    "Magisch und fantasievoll",
    "Ruhig und einschlaffreundlich",
    "Pädagogisch und ermutigend",
    "Poetisch und bildhaft",
    "Einfach und sehr verständlich",
    "Frech und lebendig",
    "Sanft und emotional",
    "Motivierend und selbstbewusst",
    "Sachlich-kindgerecht",
    "Märchenhaft und zeitlos",
    "Modern und alltagsnah"
  ]
};
